from django.urls import path
from .views import (UserAPIView, UserDeleteAPIView, UserLoginAPIView, ISPRangeListAPIView,
                    ClientRangeListAPIView, UserUpdateAPIView, ActivateAccount, ResendActivationEmail,
                    InviteUserView, SetPasswordView, PhoneRegisterView, ResendActivationCode,
                    SelfDeleteAPIView, GetProfileAPIView, ISPManagementView, VenueISPListView,
                    AdminCustomerListAPIView, CustomerManagementView, DirectISPCreateView, 
                    VenueSpecificISPListView, ManageUnlimitedAccessView, UserLoginWithVenueISPIdAPIView,
                    CustomerDetailAPIView, CustomerDeleteAPIView, VenueByISPListView, CustomersByISPListView,
                    CustomerByISPCreateView, CustomerByISPUpdateView, CustomerByISPDeleteView,
                    CustomerByISPDetailView, ClientUserListAPIView, ClientManagementView,
                    ClientTestUserView, ClientsByISPListView, ClientsByCustomerListView)

urlpatterns = [
     path('register', UserAPIView.as_view(), name='auth_register'),
     path('phone/register', PhoneRegisterView.as_view(),
          name='auth_phone_register'),
     path('login', UserLoginAPIView.as_view(), name='auth_login'),
     path('login-with-venue-isp-id', UserLoginWithVenueISPIdAPIView.as_view(),
          name='auth_login_with_venue_isp_id'),
     path('delete', UserDeleteAPIView.as_view(), name='user_delete'),
     path('update/<int:pk>', UserUpdateAPIView.as_view(), name='user-update'),
     path('isprange', ISPRangeListAPIView.as_view(), name='isp-range-list'),
     path('getprofile', GetProfileAPIView.as_view(), name='get-profile'),
     path('clientrange', ClientRangeListAPIView.as_view(), name='client-range-list'),
     path('id/<int:pk>', UserAPIView.as_view(), name='get-user-by-id'),
     path('activate', ActivateAccount.as_view(), name='activate'),
     path('phone/activate/<str:otp>',
          PhoneRegisterView.as_view(), name='activate_phone'),
     path('phone/resend/<int:pk>', ResendActivationCode.as_view(),
          name='resend_activation'),
     path('resend-activation/', ResendActivationEmail.as_view(),
          name='resend_activation'),
     # path('invite', InviteUserView.as_view(), name='invite_user'),
     path('set_password/<token>', SetPasswordView.as_view(), name='accept_invite'),
     path('deleteaccount', SelfDeleteAPIView.as_view(), name='deactivate-acccount'),
     
     #clients
     path('client-list/', ClientUserListAPIView.as_view(), name='client-user-list'),
     path('client/manage/<int:client_id>', ClientManagementView.as_view(),
               name='client-management'),
     path('client/test-user/<int:client_id>', ClientTestUserView.as_view(), name='client-test-user'),
     path('isp/<int:isp_id>/clients/', ClientsByISPListView.as_view(),
          name='clients-by-isp-list'),
     path('customer/<int:customer_id>/clients/', ClientsByCustomerListView.as_view(),
          name='clients-by-isp-list'),
     

     path('isp/manage/', ISPManagementView.as_view(), name='isp-management'),
     path('venue/isps/', VenueISPListView.as_view(), name='venue-isp-list'),
     path('admin/customers/', AdminCustomerListAPIView.as_view(),
          name='admin-customer-list'),
     path('customer/manage/', CustomerManagementView.as_view(),
          name='customer-management'),
     path('isp/create/', DirectISPCreateView.as_view(), name='direct-isp-create'),
     path('venue/<int:venue_id>/isps/', VenueSpecificISPListView.as_view(),
          name='venue-specific-isp-list'),
     path('isp/<int:isp_id>/venues/', VenueByISPListView.as_view(),
          name='venue-by-isp-list'),
     path('isp/<int:isp_id>/customers/', CustomersByISPListView.as_view(),
          name='customers-by-isp-list'),
     path('manage-unlimited-access/', ManageUnlimitedAccessView.as_view(),
          name='manage-unlimited-access'),
     path('customer/<int:customer_id>/', CustomerDetailAPIView.as_view(),
          name='customer-detail'),
     path('customer/<int:customer_id>/delete/', CustomerDeleteAPIView.as_view(),
          name='customer-delete'),
     # New CRUD endpoints for customers by ISP ID
     path('isp/<int:isp_id>/customer/create/', CustomerByISPCreateView.as_view(),
          name='customer-by-isp-create'),
     path('isp/<int:isp_id>/customer/<int:customer_id>/', CustomerByISPDetailView.as_view(),
          name='customer-by-isp-detail'),
     path('isp/<int:isp_id>/customer/<int:customer_id>/update/', CustomerByISPUpdateView.as_view(),
          name='customer-by-isp-update'),
     path('isp/<int:isp_id>/customer/<int:customer_id>/delete/', CustomerByISPDeleteView.as_view(),
          name='customer-by-isp-delete'),
   
]
